name: Auto Merge PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PR is approved and has passed all checks
        id: check_pr
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          APPROVALS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews")

          APPROVAL_COUNT=$(echo "$APPROVALS" | jq '[.[] | select(.state=="APPROVED")] | length')

          if [ "$APPROVAL_COUNT" -ge 1 ]; then
            echo "PR is approved."
          else
            echo "PR is not approved. Exiting..."
            exit 1
          fi

      - name: Pass Pipeline
        id: pass_pipeline
        run: |
          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/agenda-services/agenda/actions/runs?event=pull_request&status=failed")

          FAILED_WORKFLOWS=$(echo "$WORKFLOW_RUNS" | jq '[.workflow_runs[] | select(.status=="failed")] | length')

          if [ "$FAILED_WORKFLOWS" -gt 0 ]; then
            echo "There are failed workflows. Exiting..."
            exit 1
          else
            echo "All workflows passed."
          fi

      - name: Auto merge PR
        if: success()
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Merging PR #$PR_NUMBER"

          # Realizar el merge
          RESPONSE=$(curl -s -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
            -d '{"merge_method": "merge"}')

          echo "Merge response: $RESPONSE"

          # Comprobar si la respuesta contiene error
          if echo "$RESPONSE" | grep -q "error"; then
            echo "Error occurred: $RESPONSE"
            exit 1
          fi

          echo "PR merged successfully!"