name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get install -y && git fetch origin master

      - name: Run check commit
        run: |
          chmod +x ./scripts/check_commit.sh && ./scripts/check_commit.sh
      - name: Run check format
        run: |
          chmod +x ./scripts/check_format.sh && ./scripts/check_format.sh
